# Generated by Django 3.2.4 on 2021-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Web design', 'Web Design'), ('Cooking', 'Cooking'), ('Gardening', 'Gardening'), ('Litter picking', 'Litter Picking')], max_length=255),
        ),
    ]
