# Generated by Django 3.2.4 on 2021-06-09 13:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering_app', '0003_volunteer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('organisations', models.ManyToManyField(to='volunteering_app.Organisation')),
                ('projects', models.ManyToManyField(to='volunteering_app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_persons',
            field=models.ManyToManyField(to='volunteering_app.ContactPerson'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_persons',
            field=models.ManyToManyField(to='volunteering_app.ContactPerson'),
        ),
    ]
