# Generated by Django 3.2.4 on 2021-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering_app', '0002_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(default='images/profile_default_picture.png', upload_to=''),
        ),
    ]
